YSMOD-356 Vis varsel (i filnavn) til saksbehandler dersom vedlegg mangler
navikt/yrkesskade-melding-mottak pull request #57
Opened 2022-05-25 14:01 UTC by erlendkri

2022-05-27 09:54 UTC, lurajon requested changes
Bra! Jeg har noen kommentarer. Vi bør kanskje vurdere en endring på Storage for å slippe å fange NPE.

2022-05-27 09:54 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/meldingmottak/services/StorageService.kt
> +        } catch (npe: NullPointerException) {
Det skal i utgangspunktet aldri fanges NPE, men heller prøve å unngås. Dersom dette er fordi det skjer en NPE i getBlob, så bør vi kanskje heller vurdere å endre koden i getBlob til å returnere null, dersom det mot formodning skulle være et tilfelle at blob ikke finnes.

2022-05-27 09:54 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/meldingmottak/vedlegg/VedleggUtil.kt
> +            else -> utledFiltype(filnavn)
Bra!

2022-05-27 09:54 UTC, lurajon commented on src/test/kotlin/no/nav/yrkesskade/meldingmottak/vedlegg/VedleggUtilTest.kt
> +        assertThat(VedleggUtil.utledFiltype(byteArrayOf(), "image.png")).isEqualTo(Filtype.PNG)
Hva skjer dersom filnavn ikke har suffix?

2022-05-27 09:54 UTC, lurajon commented on src/test/kotlin/no/nav/yrkesskade/meldingmottak/vedlegg/VedleggUtilTest.kt
> +        assertThat(VedleggUtil.utledFiltype(readPngFile(), "fil3")).isEqualTo(Filtype.PNG)
hva skjer her dersom bytes er null?

2022-05-30 07:55 UTC, olsnerik reviewed
Har ikke mer å legge til, bra feedback fra Jone :)

2022-05-30 11:00 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/meldingmottak/services/StorageService.kt
> +        } catch (npe: NullPointerException) {
Rettet til returnere null fra storage dersom en blob ikke finnes. Fjernet fanging av NPE i melding-mottak.

2022-05-30 11:01 UTC, erlendkri commented on src/test/kotlin/no/nav/yrkesskade/meldingmottak/vedlegg/VedleggUtilTest.kt
> +        assertThat(VedleggUtil.utledFiltype(byteArrayOf(), "image.png")).isEqualTo(Filtype.PNG)
La til ny test på at det returneres null når det ikke går å utlede filnavn av verken innhold eller filendelse.

2022-05-30 11:23 UTC, merged

2022-05-30 11:31 UTC, lurajon approved these changes